'use strict';

const app = $id('bjApp'), fxCanvas = $id('fxCanvas'),
  shoeStack = $id('shoeStack'), shoeN = $id('shoeN'),
  dealerHand = $id('dealerHand'), dealerScore = $id('dealerScore'), playerRow = $id('playerRow'),
  betCircle = $id('betCircle'), betStack = $id('betStack'), betAmt = $id('betAmt'),
  bankAmt = $id('bankAmt'), bankWrap = $id('bankWrap'),
  msgEl = $id('msgEl'), toastEl = $id('toastEl'), banner = $id('banner'), rack = $id('rack'),
  btnClear = $id('btnClear'), btnRebet = $id('btnRebet'), btnDeal = $id('btnDeal'),
  btnHit = $id('btnHit'), btnStand = $id('btnStand'), btnDouble = $id('btnDouble'),
  btnSplit = $id('btnSplit'), btnSurrender = $id('btnSurrender'),
  btnHint = $id('btnHint'), btnCoach = $id('btnCoach'), btnDaily = $id('btnDaily'),
  btnRun = $id('btnRun'), btnMenu = $id('btnMenu'),
  ovMenu = $id('ovMenu'), btnMenuClose = $id('btnMenuClose'),
  btnStats = $id('btnStats'), btnRules = $id('btnRules'), btnSound = $id('btnSound'),
  mAch = $id('mAch'), mTrainer = $id('mTrainer'), mChart = $id('mChart'),
  mSettings = $id('mSettings'), mFair = $id('mFair'),
  ovSettings = $id('ovSettings'), setBody = $id('setBody'), btnSettingsClose = $id('btnSettingsClose'),
  ovAch = $id('ovAch'), achBody = $id('achBody'), btnAchClose = $id('btnAchClose'),
  ovTrainer = $id('ovTrainer'), trainBody = $id('trainBody'), btnTrainerClose = $id('btnTrainerClose'),
  ovChart = $id('ovChart'), chartBody = $id('chartBody'), btnChartClose = $id('btnChartClose'),
  ovFair = $id('ovFair'), fairBody = $id('fairBody'), btnFairClose = $id('btnFairClose'),
  ovDaily = $id('ovDaily'), dailyTitle = $id('dailyTitle'), dailyBody = $id('dailyBody'), dailyRow = $id('dailyRow'),
  ovRun = $id('ovRun'), runTitle = $id('runTitle'), runBody = $id('runBody'), runRow = $id('runRow'),
  ovInsurance = $id('ovInsurance'), insText = $id('insText'), btnInsYes = $id('btnInsYes'), btnInsNo = $id('btnInsNo'),
  ovStats = $id('ovStats'), sgrid = $id('sgrid'), btnReset = $id('btnReset'), btnStatsClose = $id('btnStatsClose'),
  ovRules = $id('ovRules'), btnRulesClose = $id('btnRulesClose'),
  ovLoan = $id('ovLoan'), btnLoan = $id('btnLoan');
